/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    FHEFutureLove: {
      address: "0x204D135AAED749f1C89d25f224C378fd492757A8",
      abi: [
        {
          inputs: [],
          name: "ZamaProtocolUnsupported",
          type: "error",
        },
        {
          inputs: [],
          name: "confidentialProtocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getEncryptedSequence",
          outputs: [
            {
              internalType: "euint32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "isRegistered",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "externalEuint32",
              name: "sequenceEncrypted",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "proof",
              type: "bytes",
            },
          ],
          name: "registerSequence",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9368216,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
